name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  log-github-event-goodies:
    name: 'LOG Everything on GitHub Event'
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "${{toJSON(github.event.commits[0].message)}}"
      - name: Find JIRA ticket references
        id: jira
        uses: AsasInnab/regex-action@v1
        with:
          regex_pattern: 'JIR-[0-9]+'
          regex_flags: 'gim'
          search_string: ' My jira ticket number is JIR-ABC'
      - name: Echo JIRA reference
        run: |
          echo "My JIRA ticket number is ${{ steps.jira.outputs.first_match }}"
          if [[ ${{ steps.jira.outputs.first_match }} != null ]] ; then echo "Hello!" ; else echo "Goodbye!" ; fi
