name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - if: |
          ! contains(github.event.head_commit.message, ‘wip’)
