name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: validate commit format -- Check if HEAD commit message contains [xyz] or FAIL.
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: '\[[^]]+\]'
          flags: 'gm'
          error: 'Your  commit must contain `[..]` like "[BUGFIX] or [SDK-974]".'
